# Generated by Django 4.1.7 on 2023-04-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_commentac'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentA',
        ),
    ]
