# Generated by Django 4.1.7 on 2023-04-22 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_commentms_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdc',
            name='likes',
            field=models.ManyToManyField(related_name='likes2', to=settings.AUTH_USER_MODEL),
        ),
    ]
